### ISSUE TITLE
azure_rm_storageaccount | Always already taken. - Reason.already_exists

### ISSUE THREAD

**Issue by mvdpoel** [Azure/azure_preview_modules#125] opened 2018-09-03 12:25 UTC
Hi,

Trying to run this module but it's not idempotent. It keeps returning:

"The storage account named xxx is already taken. - Reason.already_exists"

- name: Ensure Storage Account Exists
  azure_rm_storageaccount:
    resource_group: "{{ app_resourcegroup }}"
    name: "{{ sta_name }}"
    type: "{{ sta_.type }}"
    tags: "{{ azure_tags }}"
    state: "present"

Returns:

TASK [az_create_storage_account : Ensure Storage Account Exists] *****************************************************************************************************************************************************************************
task path: /opt/ansible/roles/ansible_role_az_create_storage_account/tasks/main.yml:2
fatal: [localhost]: FAILED! => {"changed": false, "msg": "The storage account named xxx is already taken. - Reason.already_exists"}

**Comment by Fred-sun** [comment] 2018-09-04 04:34
@mvdpoel I have try to create storage account to verify idempotent on ansbile(2.6.0 and 2.6.3)  all get successfully result, could you share your ansible verison and upgrade ansible to try again( Upgrade ansible to new: sudo pip install ansible[azure] --upgrade -I ). Thanks!
```e.g.
my test result:
fred@fred-Virtual-Machine:~/task/125$ ansible-playbook  125.yml 

PLAY [create stoage account] ***************************************************

TASK [Gathering Facts] *********************************************************
ok: [127.0.0.1]

TASK [Ensure storage account exist] ********************************************
changed: [127.0.0.1]

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=0   

fred@fred-Virtual-Machine:~/task/125$ ansible-playbook  125.yml 

PLAY [create stoage account] ***************************************************

TASK [Gathering Facts] *********************************************************
ok: [127.0.0.1]

TASK [Ensure storage account exist] ********************************************
ok: [127.0.0.1]

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0

**Comment by Fred-sun** [comment] 2018-09-04 05:06
In order for the community to handle your issue effectively, You can description of the issue with this template: https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md.  Thanks

**Comment by Fred-sun** [comment] 2018-09-05 05:03
@mvdpoel Do you have try again? Could you help share your test result? Thanks!

**Comment by Fred-sun** [comment] 2018-09-07 01:56
@mvdpoel Thanks for the contribution, It seem not a bug, just name already exist or use old ansible version. Could you help share you test result or some detail info?

**Comment by Fred-sun** [comment] 2018-09-10 05:42
@mvdpoel Thanks for the contribution, Could you help recheck this issue? it seem not a bug, just the storage account name has already exist. Thanks!

**Comment by Fred-sun** [comment] 2018-09-12 05:51
@mvdpoel Thanks for the contribution. I have retested again. this module has idempotent. if the storage account has exist, will get this error. I think your account name may has been created by other credential or this account name has existed on other resource group. Thanks!.

**Comment by Fred-sun** [comment] 2018-09-14 01:54
@mvdpoel Thanks for the contribution, Could you help retry and share you test result to us? Thanks!

**Comment by Fred-sun** [comment] 2018-09-19 06:05
@mvdpoel thanks for the contribution. Are you still here? do you still have this question? Thanks!

**Comment by Fred-sun** [comment] 2018-10-16 01:59
@mvdpoel thanks for the contribution. Are you still here? Could we can close this issue？ Thanks!

**Comment by Fred-sun** [comment] 2018-10-30 09:07
@yuwzho @yungezz The issue has no update more than one month,  I have tested, this is not a bug, Could we can close this issue? Thanks!

**Comment by Fred-sun** [comment] 2018-11-12 07:45
@mvdpoel Thanks for you contribution, Are you still here? Could we can close this issue( not a bug)? Thanks!

**Comment by Fred-sun** [comment] 2018-11-23 06:03
@yungezz Could you help check this issue? this may not a bug, just the storageaccount name already in resource. Thanks!

**Comment by Fred-sun** [comment] 2018-12-03 09:09
@yungezz Could we can close the problem?  re-open it when we encounter it again, and ask contributors for more information. Thanks!

**Comment by Fred-sun** [comment] 2018-12-13 03:04
not a bug, can be closed.

**Closed as completed** 2018-12-13 03:29 UTC

**Comment by michael-niemand** [comment] 2020-01-10 13:57
To anybody arriving here via Google, looking for an answer: As the [documentation](https://docs.microsoft.com/en-us/azure/storage/common/storage-account-create?tabs=azure-cli#create-a-storage-account) states, **storage account names have to be unique across all of Azure**.
There are most likely more elegant ways to solve this, but here's what I did: 
`azure_k8s_cluster_sa_name: "{{ 'mystorage' | to_uuid | lower | replace('-', '') | truncate(24, True, '') }}"`
