### ISSUE TITLE
Error creating the Database Account instance: 400 Client Error:

### ISSUE THREAD

**Issue by adithyakhamithkar** [Azure/azure_preview_modules#220] opened 2019-03-11 08:03 UTC
I am getting this error while creating a cosmosdb

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating the Database Account instance: 400 Client Error: BadRequest for url: https://management.azure.com/subscriptions/xxxxxxxxxxxxx/resourceGroups/xxxxxx/providers/Microsoft.DocumentDB/databaseAccounts/xxxxxx?api-version=2015-04-08"}
```
Can someone please help me debug this?

**Comment by zikalino** [comment] 2019-03-12 03:41
@adithyakhamithkar could you give some more details, for instance the playbook you're using?

**Comment by zikalino** [comment] 2019-03-13 01:37
@adithyakhamithkar I have rechecked the playbook, and one possible problem is the name of cosmos db account. it needs to be unique, and the service doesn't report error correctly if it's not unique (just returns 400)…
I am going to add appropriate name availability check to the module.
in a meanwhile could you check the same playbook with different cosmos db account name?

**Comment by adithyakhamithkar** [comment] 2019-03-13 01:54
I have tried with different names. Can you please help me with the naming convention?
Does the DB account name have to be unique universally or unique in the resource group?

**Comment by zikalino** [comment] 2019-03-13 01:57
unique globally, because it's going to be a part of domain name.
so it's good to have some random part of the name.

I just tried db with following name:

"https://mycosmosdbaccountxyzmdifuy.documents.azure.com:443/"

When I tried with just simple name like "mycosmosdb" I got the same error as you:

TASK [Create instance of Cosmos DB Account] *********************************************************************************************************************************************
 [WARNING]: Azure API profile latest does not define an entry for CosmosDB

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating the Database Account instance: 400 Client Error: BadRequest for url: https://management.azure.com/subscriptions/xxxxxxx/resourceGroups/zimscosmosrg/providers/Microsoft.DocumentDB/databaseAccounts/mycosmosdbaccount?api-version=2015-04-08"}
        to retry, use: --limit @/mnt/c/dev/ansible-playbooks/cosmosdb_create.retry

**Comment by adithyakhamithkar** [comment] 2019-03-13 02:05
I am trying with a really random name I am sure it would be unique
```
 [WARNING]: Azure API profile latest does not define an entry for CosmosDB

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating the Database Account instance: 400 Client Error: BadRequest for url: https://management.azure.com/subscriptions/****/resourceGroups/****/providers/Microsoft.DocumentDB/databaseAccounts/yqdfinfjgqsqimvkbqih?api-version=2015-04-08"}
```

**Comment by Fred-sun** [comment] 2019-03-18 03:32
@zikalino Could you give a solution according to the error described in the Issue? Thanks!

**Comment by zikalino** [comment] 2019-03-22 04:19
@adithyakhamithkar i just found one more reason for 400 failure.
cosmosdb account name shouldn't include any uppercase characters.
could that be a reason of the failure in your case?

i guess i should add this check to the module.

**Comment by adithyakhamithkar** [comment] 2019-03-22 04:21
I used all lower case characters also but still I got the error. This was my account name `yqdfinfjgqsqimvkbqih`

**Comment by zikalino** [comment] 2019-03-22 04:25
yeah, i can see that now.... i just checked exactly the same name "yqdfinfjgqsqimvkbqih" and it works for me. so it must be something else.
seems like api is very sensitive and not very helpful when it comes to providing reason for failure :-(

**Comment by zikalino** [comment] 2019-03-22 04:31
ok, i think there's something wrong with "kind" option, could you just comment it out and try the playbook again? maybe use different random name just to make sure it's not causing problems

**Comment by adithyakhamithkar** [comment] 2019-03-22 04:37
Yes "kind" was the problem now I am able to create it. Can you please give me the valid options of "kind"

**Comment by zikalino** [comment] 2019-03-22 04:40
this should be valid  option. I am just creating a pr to fix this. I guess again there's something with internal lowercase to uppercase conversion. I will let you know when the fix is in.

btw, is there any additional functionality you may need to use cosmos db in ansible?

**Comment by adithyakhamithkar** [comment] 2019-03-22 04:53
Yes I just noticed one more thing. 
When I want to update any parameters for an existing database account I get 400 Client Error. Ideally when the state=present it should update the existing database account.

**Comment by zikalino** [comment] 2019-03-22 04:55
unfortunately some parameters can't be updated.
I am planning to add appropriate warnings for this.

**Comment by adithyakhamithkar** [comment] 2019-03-22 04:59
That sounds great as long as we get appropriate warnings.

Also geo_rep_locations says I can pass an array but am not able to pass more than one.

**Comment by zikalino** [comment] 2019-03-22 05:03
pls check here: https://github.com/ansible/ansible/blob/e69828e285a4cbc847b06ef4c743806353bcf655/test/integration/targets/azure_rm_cosmosdbaccount/tasks/main.yml#L47

this is a part of the integration test.

**Comment by adithyakhamithkar** [comment] 2019-03-22 05:31
Thanks a lot I'll get back to you with more feedback and question as I am going to explore more on cosmos db in ansible

**Comment by zikalino** [comment] 2019-03-22 05:59
@adithyakhamithkar   thanks a lot for testing it for me :-)
I will be more than happy to fix / add any features you may need!

**Comment by adithyakhamithkar** [comment] 2019-03-25 04:50
@zikalino I noticed that even after adding these parameters
```
is_virtual_network_filter_enabled: yes
    virtual_network_rules:
      - subnet:
          resource_group: "{{pl_resource_group_name}}"
          virtual_network_name: "{{pl_virtualnetwork_name}}"
          subnet_name: "{{pl_subnet_name}}"
        ignore_missing_vnet_service_endpoint: yes
```
The virtual network filters are not being applied I had to add the manually and is there any settings I can enable for these?
Accept connections from within public Azure datacenters
Allow access from Azure Portal - I had to add this manually

**Comment by zikalino** [comment] 2019-03-25 04:54
@adithyakhamithkar the endpoints need to be enabled in the subnet.
unfortunately these endpoints are not immediately populates, so "ignoree_missing_vnet_service_endpoints" parameter is needed, when you create cosmos db right after creating subnet.

regarding keyspace & table management I will look into this and add it.

**Comment by adithyakhamithkar** [comment] 2019-03-25 04:57
Let me look for a work around to get the subnet endpoints 
Can you please suggest me what can be done for these
Accept connections from within public Azure datacenters
Allow access from Azure Portal

**Comment by Fred-sun** [comment] 2019-03-27 08:32
@zikalino Could you please help to answer this question when you're available? Thanks!

**Comment by Fred-sun** [comment] 2019-04-11 08:15
@zikalino

**Comment by Fred-sun** [comment] 2019-04-23 09:55
@zikalino Can you help resolve contributors' doubts? Thanks!

**Comment by Fred-sun** [comment] 2019-05-31 08:05
@zikalino Can you give contributors some insight or methodology? Thanks a lot!

**Comment by Fred-sun** [comment] 2019-07-22 08:25
@zikalino How did you deal with this problem? Could you update the status of the solution? Thank you very much!

**Comment by Fred-sun** [comment] 2019-08-19 08:06
@zikalino How is this going? Since it has been described in azure_rm_comosacountdb that 'kind' can only be used for creation, is this problem supposed to be caused by the wrong use of parameters? Can we turn it off? Please check! Thank you very much!
https://github.com/Azure/azure_preview_modules/blob/bfda7a62cb9fe92fe47a58d693cfb8be28517837/library/azure_rm_cosmosdbaccount.py#L39

**Comment by Fred-sun** [comment] 2019-09-09 02:44
> this should be valid  option. I am just creating a pr to fix this. I guess again there's something with internal lowercase to uppercase conversion. I will let you know when the fix is in.
> btw, is there any additional functionality you may need to use cosmos db in ansible?

@zikalino Any update for the new PR?

**Comment by Fred-sun** [comment] 2019-10-11 06:13
@zikalino Are you still pay attention on this issue? Please send PR to fix this problem when you are free. Thank you very much!

**Comment by Fred-sun** [comment] 2019-10-30 07:13
kindly ping!

**Comment by Fred-sun** [comment] 2019-11-21 03:15
@adithyakhamithkar Do you still have this problem? Please share! Thank you very mcuh!

**Comment by adithyakhamithkar** [comment] 2019-11-21 10:59
It's not a major problem we can close it.

Thanks for the follow up @Fred-sun

**Comment by Fred-sun** [comment] 2019-11-22 02:08
close_me

**Comment by Fred-sun** [comment] 2020-01-03 02:52
> It's not a major problem we can close it.
> Thanks for the follow up @Fred-sun

Thanks , I will close this!

**Closed by Fred-sun** 2020-01-03 02:52 UTC
