### ISSUE TITLE
azure_rm_hdinsightcluster creation failing 

### ISSUE THREAD

**Issue by adithyakhamithkar** [Azure/azure_preview_modules#263] opened 2019-05-17 05:32 UTC
I am using Ansible version: 2.8.0 to create HDinsights cluster but I am getting this error

```
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1558070366.18-101606109807868/AnsiballZ_azure_rm_hdinsightcluster.py", line 114, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1558070366.18-101606109807868/AnsiballZ_azure_rm_hdinsightcluster.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1558070366.18-101606109807868/AnsiballZ_azure_rm_hdinsightcluster.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_azure_rm_hdinsightcluster_payload_T09hfG/__main__.py", line 555, in <module>
  File "/tmp/ansible_azure_rm_hdinsightcluster_payload_T09hfG/__main__.py", line 551, in main
  File "/tmp/ansible_azure_rm_hdinsightcluster_payload_T09hfG/__main__.py", line 252, in __init__
  File "/tmp/ansible_azure_rm_hdinsightcluster_payload_T09hfG/ansible_azure_rm_hdinsightcluster_payload.zip/ansible/module_utils/azure_rm_common.py", line 325, in __init__
  File "/tmp/ansible_azure_rm_hdinsightcluster_payload_T09hfG/__main__.py", line 337, in exec_module
  File "/tmp/ansible_azure_rm_hdinsightcluster_payload_T09hfG/__main__.py", line 366, in create_update_cluster
  File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/hdinsight/operations/clusters_operations.py", line 122, in create
    **operation_config
  File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/hdinsight/operations/clusters_operations.py", line 75, in _create_initial
    response = self._client.send(request, stream=False, **operation_config)
  File "/usr/local/lib/python2.7/dist-packages/msrest/service_client.py", line 219, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/msrest/pipeline/__init__.py", line 203, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/usr/local/lib/python2.7/dist-packages/msrest/pipeline/__init__.py", line 156, in send
    response = self.next.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/msrest/pipeline/requests.py", line 72, in send
    return self.next.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/msrest/pipeline/requests.py", line 137, in send
    return self.next.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/msrest/pipeline/__init__.py", line 156, in send
    response = self.next.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/msrest/pipeline/requests.py", line 193, in send
    self.driver.send(request.http_request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/msrest/universal_http/requests.py", line 328, in send
    return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/msrest/universal_http/requests.py", line 140, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/usr/local/lib/python2.7/dist-packages/msrest/exceptions.py", line 57, in raise_with_traceback
    raise error
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/xxx/resourceGroups/xx/providers/Microsoft.HDInsight/clusters/xxx?api-version=2015-03-01-preview (Caused by ResponseError('too many 500 error responses',))
```

This is my Playbook
```
- name: Create instance of HDInsight Cluster
  azure_rm_hdinsightcluster:
    resource_group: "{{pl_resource_group_name}}"
    name: "{{pl_hdinsight_name}}"
    location: "{{pl_location}}"
    cluster_version: "{{pl_hdinsight_cluster_version}}"
    os_type: "{{pl_hdinsight_os_type}}"
    tier: "{{pl_hdinsight_tire}}"
    cluster_definition:
      kind: "{{pl_hdinsight_kind}}"
      gateway_rest_username: "{{pl_gateway_rest_username}}"
      gateway_rest_password: "{{pl_gateway_rest_password}}"
    storage_accounts:
      - name: "{{pl_blob_name}}"
        is_default: yes
        container: "{{pl_blob_name}}"
        key: "{{pl_create_storageaccount_output.stdout}}"
    compute_profile_roles:
      - name: headnode
        target_instance_count: "{{pl_hdinsight_headnode_vm_count}}"
        hardware_profile:
          vm_size: "{{pl_hdinsight_headnode_vm_size}}"
        linux_profile:
          username: "{{pl_gateway_rest_username}}"
          password: "{{pl_gateway_rest_password}}"
      - name: workernode
        target_instance_count: "{{pl_hdinsight_workernode_vm_count}}"
        vm_size: "{{pl_hdinsight_workernode_vm_size}}"
        linux_profile:
          username: "{{pl_gateway_rest_username}}"
          password: "{{pl_gateway_rest_password}}"
    state: present
    auth_source: env
  environment:
    AZURE_SUBSCRIPTION_ID: '{{pl_azure_subscription_id}}'
    AZURE_CLIENT_ID: '{{pl_azure_client_id}}'
    AZURE_SECRET: '{{pl_azure_secret}}'
    AZURE_TENANT: '{{pl_azure_tenant}}'
```

**Comment by yuwzho** [comment] 2019-05-17 07:46
Thanks for your reporting, @zikalino will take a look

Besides this, you can take our integration test as a refer

https://github.com/ansible/ansible/blob/dfab364a19c15dc3ab0d1e86a6a67bf755fe426d/test/integration/targets/azure_rm_hdinsightcluster/tasks/main.yml#L71-L106

**Comment by Fred-sun** [comment] 2019-05-28 02:13
@adithyakhamithkar Thanks for your contribution, I can easy reproduce your problem, It may caused by your storage_account's name value define error.  The name should be the storage account's blob service endpoint, such as "name: storage_account_name.blob.core.windwos.net". Could you can try again?or you can share your storage_accounts's  parameter let me try? Thanks a lot!

**Comment by Fred-sun** [comment] 2019-05-28 02:19
Or can you reference this example---[71->107 line](https://github.com/ansible/ansible/blob/devel/test/integration/targets/azure_rm_hdinsightcluster/tasks/main.yml)? Thank you very much!

**Comment by adithyakhamithkar** [comment] 2019-05-28 04:13
Thanks a lot that sorted the problem!

**Comment by Fred-sun** [comment] 2019-05-28 05:11
Thanks for your try. If you have no other proble, we can closed this. Thank you very much!

**Closed** 2019-05-28 05:20 UTC
