### ISSUE TITLE
storage_mb parameter is not working in azure_rm_postgresqlserver

### ISSUE THREAD

**Issue by dgalpaj** [Azure/azure_preview_modules#151] opened 2018-11-09 11:13 UTC
I can see the storage_mb is always configured with a default value for 5GB.
I'm executing the following provision in the module:

```
TASK [Create ADP server instance] *************************************************************************************************************************************************
task path: /home/baikal/delivery/ansible/playbook_infra_create_15_dbaas_azure.yml:40
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/cloud/azure/azure_rm_postgresqlserver.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'AZURE_SUBSCRIPTION_ID=xxxxxxxxx python && sleep 0'
 [WARNING]: Azure API profile latest does not define an entry for PostgreSQLManagementClient

changed: [localhost] => {
    "changed": true,
    "fully_qualified_domain_name": "adptest-db.postgres.database.azure.com",
    "id": "/subscriptions/xxxxxxxxx/resourceGroups/adptest-rg/providers/Microsoft.DBforPostgreSQL/servers/adptest-db",
    "invocation": {
        "module_args": {
            "ad_user": null,
            "adfs_authority_url": null,
            "admin_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "admin_username": "postgres",
            "api_profile": "latest",
            "auth_source": null,
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "create_mode": "Default",
            "enforce_ssl": false,
            "location": "northeurope",
            "name": "adptest-db",
            "password": null,
            "profile": null,
            "resource_group": "adptest-rg",
            "secret": null,
            "sku": {
                "capacity": "4",
                "name": "GP_Gen5_4",
                "tier": "GeneralPurpose"
            },
            "state": "present",
            "storage_mb": 307200,
            "subscription_id": null,
            "tenant": null,
            "version": "10"
        }
    },
    "state": "Ready",
    "version": "10"
}
```
After the ansible module execution I can check the postgres server configuration and I can find the following:

```
$ az postgres server show --resource-group adptest-rg --name adptest-db
{
  "administratorLogin": "postgres",
  "earliestRestoreDate": "2018-11-09T11:07:05.180000+00:00",
  "fullyQualifiedDomainName": "adptest-db.postgres.database.azure.com",
  "id": "/subscriptions/xxxxxxxxxx/resourceGroups/adptest-rg/providers/Microsoft.DBforPostgreSQL/servers/adptest-db",
  "location": "northeurope",
  "name": "adptest-db",
  "resourceGroup": "adptest-rg",
  "sku": {
    "capacity": 4,
    "family": "Gen5",
    "name": "GP_Gen5_4",
    "size": null,
    "tier": "GeneralPurpose"
  },
  "sslEnforcement": "Disabled",
  "storageProfile": {
    "backupRetentionDays": 7,
    "geoRedundantBackup": "Disabled",
    "storageMb": 5120
  },
  "tags": null,
  "type": "Microsoft.DBforPostgreSQL/servers",
  "userVisibleState": "Ready",
  "version": "10"
}
```
Where you can see the storageMb capacity of the database server has been provisioned with 5Gb instead the value specified in storage_mb param of azure_rm_postgresqlserver for 300 Gb.

As workaround, after the database server provision I'm executing the following command:
```
az postgres server update --storage-size 307200 --resource-group adptest-rg --name adptest-db
```
Now if we check again the current configuration of the database instance we can see it has been correctly provisioned:
```
$ az postgres server show --resource-group adptest-rg --name adptest-db
{
  "administratorLogin": "postgres",
  "earliestRestoreDate": "2018-11-09T11:07:05.180000+00:00",
  "fullyQualifiedDomainName": "adptest-db.postgres.database.azure.com",
  "id": "/subscriptions/xxxxxxx/resourceGroups/adptest-rg/providers/Microsoft.DBforPostgreSQL/servers/adptest-db",
  "location": "northeurope",
  "name": "adptest-db",
  "resourceGroup": "adptest-rg",
  "sku": {
    "capacity": 4,
    "family": "Gen5",
    "name": "GP_Gen5_4",
    "size": null,
    "tier": "GeneralPurpose"
  },
  "sslEnforcement": "Disabled",
  "storageProfile": {
    "backupRetentionDays": 7,
    "geoRedundantBackup": "Disabled",
    "storageMb": 307200
  },
  "tags": null,
  "type": "Microsoft.DBforPostgreSQL/servers",
  "userVisibleState": "Ready",
  "version": "10"
}
```

**Comment by Fred-sun** [comment] 2018-11-23 05:41
@zikalino

**Comment by Fred-sun** [comment] 2018-12-06 06:31
@zikalino

**Comment by Fred-sun** [comment] 2018-12-18 08:16
@zikalino this duplicate of #48415, may be we can close this and pay more attention on another. Thanks!

**Comment by Fred-sun** [comment] 2018-12-28 07:17
@zikalino

**Comment by Fred-sun** [comment] 2019-01-29 03:03
@zikalino

**Comment by Fred-sun** [comment] 2019-02-18 08:42
@zikalino

**Comment by zikalino** [comment] 2019-02-20 03:15
this is already fixed in ansible / devel, so it should be propagated here very soon

**Comment by Fred-sun** [comment] 2019-02-27 02:36
to_be_closed , It has been fixed on latest version. Thanks!

**Comment by Fred-sun** [comment] 2019-03-12 03:38
ping

**Comment by zikalino** [comment] 2019-03-12 03:39
just closing as fixed

**Closed by zikalino** 2019-03-12 03:39 UTC

**Comment by dgalpaj** [comment] 2019-03-12 11:27
yes, right, I have tested and it is working fine now.

Great job!
