### ISSUE TITLE
azure API limits returns first 50 results

### ISSUE THREAD

**Issue by MarianoRubio** [Azure/azure_preview_modules#203] opened 2019-02-21 12:39 UTC
Azure API limits return to 50 results, need to make the page limit when wrapping an API call transparent. Otherwise azure_rm_resource_facts works when you have less than 50 resources...
Anyone faces the same issue?

**Comment by Fred-sun** [comment] 2019-02-22 05:59
@yungezz Could you please take a look this question when you're available? Thanks!

**Comment by yungezz** [comment] 2019-02-22 06:10
@MarianoRubio  which Azure API are you using? if the api paged? you might want to iterate next_page_token . Is this a general Azure question or Ansible on Azure issue?

**Comment by MarianoRubio** [comment] 2019-02-22 09:52
@yungezz 

API version is 2018-10-01, and yes it is paged, (Are there non paged versions? that would short it) I would say Ansible as the API paging the results is common but the module should be the one handling that loop until next_page_token is empty.

**Comment by MarianoRubio** [comment] 2019-02-25 17:03
> @MarianoRubio which Azure API are you using? if the api paged? you might want to iterate next_page_token . Is this a general Azure question or Ansible on Azure issue?

**Comment by MarianoRubio** [comment] 2019-02-26 10:07
- Closed by mistake sorry

**Comment by yungezz** [comment] 2019-02-27 07:45
@MarianoRubio  are you using azure_rm_resource module?

**Comment by MarianoRubio** [comment] 2019-02-27 11:56
Hi @yungezz  im using literally like bellow.

- name: Get instances
   azure_rm_resource_facts:
        api_version: "2018-10-01"
        provider: compute
        resource_type: virtualmachines
        cert_validation_mode: "ignore"
    register: instance_facts

**Comment by yungezz** [comment] 2019-02-28 02:01
HI @zikalino could you pls look at the paging issue in azure_rm_resource_facts?

**Comment by zikalino** [comment] 2019-02-28 02:04
@yungezz @MarianoRubio I will fix it asap

**Comment by zikalino** [comment] 2019-03-08 02:15
@MarianoRubio I already know how this should be fixed, however I am having some problems reproducing this issue. Basically I am trying to query resources, and I am getting responses with more than 50 items without paging:

My current playbook looks like this:
```yaml
  - name: Query Subnets
    azure_rm_resource_facts:
      api_version: '2018-08-01'
      resource_group: "{{ resource_group }}"
      provider: network
      resource_type: virtualnetworks
      resource_name: myvn
      subresource:
        - type: subnets
    register: output
  - debug:
      msg: list lenght {{ output['response'][0]['value'] | length }}

  - name: Query virtual machines in subscription
    azure_rm_resource_facts:
      api_version: '2018-10-01'
      provider: compute
      resource_type: virtualmachines
    register: output

  - debug:
      msg: list lenght {{ output['response'][0]['value'] | length }}
```

and response

```
TASK [Query Subnets] ********************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] ****************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "list length 60"
}

TASK [Query virtual machines in subscription] *******************************************************************************************************************************************
ok: [localhost]

TASK [debug] ****************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "list length 54"
}

PLAY RECAP ******************************************************************************************************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Comment by zikalino** [comment] 2019-03-08 03:21
Ok, I managed to reproduce this with following task:
```yaml
  - name: Query All resources in subsciprion
    azure_rm_resource_facts:
      api_version: '2018-08-01'
      resource_type: resources
    register: output
  - debug:
      msg: list length {{ output['response'][0]['value'] | length }}

  - debug:
      msg: next {{ output['response'][0]['nextLink'] }}
```

Return value was:

```json
TASK [debug] ****************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "list length 1000"
}

TASK [debug] ****************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "next https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resources?api-version=2018-08-01&%24skiptoken=......................"
}

```

**Comment by zikalino** [comment] 2019-03-08 03:57
fixed this upstream: https://github.com/ansible/ansible/pull/53500

**Comment by Fred-sun** [comment] 2019-03-11 09:45
The PR [#53500](https://github.com/ansible/ansible/pull/53500) has been merged, to_be_closed

**Comment by zikalino** [comment] 2019-03-12 03:42
closing, should be propagated to preview modules soon too.

**Closed by zikalino** 2019-03-12 03:42 UTC
